### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mushkanT** [Lekhraj1729/Image_Processing#3]
Error using load
Unable to read file 'GUIDE_gen_file.fig'. No such file or directory.

Error in matlab.graphics.internal.figfile.FigFile/read (line 31)
hgDataVars = load(filename, '-mat', '-regexp', '^hg[M]');

Error in matlab.graphics.internal.figfile.FigFile

Error in hgload (line 50)
FF = matlab.graphics.internal.figfile.FigFile(filename);

Error in matlab.hg.internal.openfigLegacy (line 57)
    [fig, savedvisible] = hgload(filename, struct('Visible','off'));

Error in gui_mainfcn>local_openfig (line 286)
    gui_hFigure = matlab.hg.internal.openfigLegacy(name, singleton, visible);

Error in gui_mainfcn (line 158)
        gui_hFigure = local_openfig(gui_State.gui_Name, gui_SingletonOpt,
        gui_Visible);

Error in GUIDE_gen_file (line 42)
    gui_mainfcn(gui_State, varargin{:});

**Comment by mushkantisekar** [comment]
after changing test2 name to GUIDE_gen_file.fig
Error while evaluating UIControl Callback.

Undefined function or variable 'test2'.

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)test2('pushbutton1_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating UIControl Callback.

Undefined function or variable 'test2'.

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)test2('pushbutton1_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating UIControl Callback.

**Comment by mushkantisekar** [comment]
c
